### ISSUE TITLE
forge版-qq群收不到forge1.16.5的消息

### ISSUE THREAD

**Issue by ayakasuki** [17TheWord/MC_QQ_Forge#1]
```
07-09 17:19:10 [SUCCESS] mcqq_tool | [MC_QQ_Rcon]丨发送至 [server:Server] 的消息 "27. 说：没看到你窝"
07-09 17:19:10 [INFO] nonebot | Matcher <Matcher from extensive_plugin.nonebot_plugin_mcqq, type=message, priority=2, temp=False> running complete
07-09 17:21:05 [ERROR] uvicorn | Exception in ASGI application

Traceback (most recent call last):
  File "/bot/bot.py", line 23, in <module>
    nonebot.run()
  File "/usr/local/lib/python3.9/site-packages/nonebot/__init__.py", line 261, in run
    get_driver().run(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/nonebot/drivers/fastapi.py", line 170, in run
    uvicorn.run(
  File "/usr/local/lib/python3.9/site-packages/uvicorn/main.py", line 576, in run
    server.run()
  File "/usr/local/lib/python3.9/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/local/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
> File "/usr/local/lib/python3.9/site-packages/uvicorn/protocols/websockets/websockets_impl.py", line 225, in run_asgi
    result = await self.app(self.scope, self.asgi_receive, self.asgi_send)
  File "/usr/local/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/fastapi/applications.py", line 269, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 149, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/cors.py", line 76, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/exceptions.py", line 69, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/usr/local/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 670, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 325, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 81, in app
    await func(session)
  File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 279, in app
    await dependant.call(**values)
  File "/usr/local/lib/python3.9/site-packages/nonebot/drivers/fastapi.py", line 125, in _handle
    await self._handle_ws(websocket, setup)
  File "/usr/local/lib/python3.9/site-packages/nonebot/drivers/fastapi.py", line 237, in _handle_ws
    await setup.handle_func(ws)
  File "/bot/extensive_plugin/nonebot_plugin_mcqq/data_source.py", line 63, in _ws_handler
    await send_msg_to_qq(bot=bot, message=message)
  File "/usr/local/lib/python3.9/site-packages/mcqq_tool/utils.py", line 135, in send_msg_to_qq
    await _send_msg_to_qq_common(
  File "/usr/local/lib/python3.9/site-packages/mcqq_tool/common.py", line 55, in _send_msg_to_qq_common
    event = event_dict[json_msg["event_name"]].parse_obj(json_msg)
KeyError: 'ForgeServerChatEvent'
```
群聊天能发送到游戏，游戏是显示的，但是MC里的发送不到QQ群

**Comment by 17TheWord** [comment]
最近一次的重写中还未更新forge，请等更新

**Comment by ayakasuki** [comment]
> 最近一次的重写中还未更新forge，请等更新

好的 谢谢大佬

**Comment by 17TheWord** [comment]
> > 最近一次的重写中还未更新forge，请等更新
> 
> 好的 谢谢大佬

可以试试之前的nb插件版本，往前翻的话总会有配套能用的，不过需要多尝试，时间上来算的话一个月以前的。

**Comment by ayakasuki** [comment]
> > > 最近一次的重写中还未更新forge，请等更新
> > 
> > 
> > 好的 谢谢大佬
> 
> 可以试试之前的nb插件版本，往前翻的话总会有配套能用的，不过需要多尝试，时间上来算的话一个月以前的。

大佬 弱弱问一句后面会适配fabric端嘛

**Comment by 17TheWord** [comment]
> > > > 最近一次的重写中还未更新forge，请等更新
> > > 
> > > 
> > > 好的 谢谢大佬
> > 
> > 
> > 可以试试之前的nb插件版本，往前翻的话总会有配套能用的，不过需要多尝试，时间上来算的话一个月以前的。
> 
> 大佬 弱弱问一句后面会适配fabric端嘛

fabricmod我不会写，上次试了试没找到头绪，如果能写出来的话就简单做一下了，端太多，每次更新都要写好多东西

**Comment by 17TheWord** [comment]
> > > > 最近一次的重写中还未更新forge，请等更新
> > > 
> > > 
> > > 好的 谢谢大佬
> > 
> > 
> > 可以试试之前的nb插件版本，往前翻的话总会有配套能用的，不过需要多尝试，时间上来算的话一个月以前的。
> 
> 大佬 弱弱问一句后面会适配fabric端嘛

Fabric已发第一版，暂时只支持1.20.1以及Rcon发送消息，欢迎使用或PR [MC_QQ_Forge](https://github.com/17TheWord/MC_QQ_Fabric)
